export type Language = 'en' | 'bm' | 'zh' | 'ta';

export const languageOptions: {
  code: Language;
  label: string;
  native: string;
  glyph: string;
  ready: boolean;
}[] = [
  { code: 'en', label: 'English', native: 'English', glyph: 'EN', ready: true },
  { code: 'bm', label: 'Bahasa Malaysia', native: 'Bahasa Malaysia', glyph: 'BM', ready: true },
  { code: 'zh', label: 'Chinese', native: '中文', glyph: '中', ready: true },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்', glyph: 'த', ready: true },
];

export function languageName(language: Language) {
  return languageOptions.find((option) => option.code === language)?.label ?? 'English';
}

export type Translate = (source: string, values?: Record<string, string | number>) => string;

export function translate(language: Language, source: string, values?: Record<string, string | number>): string {
  const lookupSource = language === 'en' ? source : source.replaceAll('\u00a0', ' ');
  const translated: string = language === 'en' ? source : dictionaries[language][lookupSource] ?? financeDictionaries[language][lookupSource] ?? uiDictionaries[language][lookupSource] ?? translateDynamic(language, lookupSource) ?? lookupSource;
  if (!values) return translated;
  return Object.entries(values).reduce((text, [key, value]) => text.replaceAll(`{${key}}`, String(value)), translated);
}

function translateDynamic(language: Exclude<Language, 'en'>, source: string): string | null {
  for (const suffix of ['Adjusted proportionally because fixed shares exceed the estate.', 'Residue returned proportionally by radd estimate.']) {
    if (source.endsWith(` ${suffix}`)) {
      const base = source.slice(0, -(suffix.length + 1));
      return `${translate(language, base)} ${translate(language, suffix)}`;
    }
  }
  if (source.includes(' · ')) return source.split(' · ').map((part) => translate(language, part)).join(' · ');
  const shortYears = source.match(/^(\d+)y$/);
  if (shortYears) return language === 'bm' ? `${shortYears[1]} thn` : language === 'zh' ? `${shortYears[1]} 年` : `${shortYears[1]} ஆண்டு`;
  const summaryAmount = source.match(/^(RM [\d,.]+) (income|balance)$/);
  if (summaryAmount) return `${summaryAmount[1]} ${translate(language, summaryAmount[2] === 'income' ? 'income' : 'balance')}`;
  const monthlyAmount = source.match(/^\+? ?(RM [\d,.]+)\/mo$/);
  if (monthlyAmount) return `${monthlyAmount[1]}/${translate(language, 'mo')}`;
  const stampDuty = source.match(/^([\d.]+%) stamp duty$/);
  if (stampDuty) return `${stampDuty[1]} ${translate(language, 'stamp duty')}`;
  const vehicle = source.match(/^(New|Used) vehicle$/);
  if (vehicle) {
    const condition = translate(language, vehicle[1]).toLowerCase();
    if (language === 'bm') return `Kereta ${condition}`;
    if (language === 'zh') return vehicle[1] === 'New' ? '新车' : '二手车';
    return `${condition} கார்`;
  }
  const children = source.match(/^(\d+) children entered$/);
  if (children) return language === 'bm' ? `${children[1]} anak dimasukkan` : language === 'zh' ? `已填 ${children[1]} 名子女` : `${children[1]} பிள்ளைகள் சேர்க்கப்பட்டனர்`;
  const amountFinanced = source.match(/^(RM [\d,.]+) financed after (RM [\d,.]+) down payment\.$/);
  if (amountFinanced) return language === 'bm' ? `${amountFinanced[1]} dibiayai selepas bayaran muka ${amountFinanced[2]}.` : language === 'zh' ? `首付 ${amountFinanced[2]}，贷款 ${amountFinanced[1]}。` : `${amountFinanced[2]} முன்பணம் கட்டிய பிறகு ${amountFinanced[1]} கடன்.`;

  const methodYears = source.match(/^(Reducing-balance|Flat-rate) method over ([\d.]+) years\.$/);
  if (methodYears) {
    const method: string = translate(language, methodYears[1] === 'Reducing-balance' ? 'Reducing' : 'Flat');
    return language === 'bm' ? `Kaedah ${method} untuk ${methodYears[2]} tahun.` : language === 'zh' ? `${method}，期限 ${methodYears[2]} 年。` : `${method} முறை, ${methodYears[2]} ஆண்டுகள்.`;
  }

  const cardPaid = source.match(/^(RM [\d,.]+) paid including (RM [\d,.]+) finance charge\.$/);
  if (cardPaid) return language === 'bm' ? `Jumlah bayar ${cardPaid[1]}, termasuk caj kewangan ${cardPaid[2]}.` : language === 'zh' ? `总共还 ${cardPaid[1]}，包括 ${cardPaid[2]} 财务费。` : `மொத்தம் ${cardPaid[1]} கட்டுவீர்கள்; அதில் ${cardPaid[2]} நிதிக் கட்டணம்.`;

  const balanceRemains = source.match(/^Projected balance remains (RM [\d,.]+) after (\d+) months\.$/);
  if (balanceRemains) return language === 'bm' ? `Selepas ${balanceRemains[2]} bulan, baki dianggarkan masih ${balanceRemains[1]}.` : language === 'zh' ? `${balanceRemains[2]} 个月后，预计还剩 ${balanceRemains[1]}。` : `${balanceRemains[2]} மாதங்களுக்குப் பிறகும் ${balanceRemains[1]} மீதி இருக்கும்.`;

  const ujrahMethod = source.match(/^(Reducing-balance|Flat-rate) Ujrah planning estimate\.$/);
  if (ujrahMethod) {
    const method: string = translate(language, ujrahMethod[1] === 'Reducing-balance' ? 'Reducing' : 'Flat');
    return language === 'bm' ? `Anggaran Ujrah menggunakan kaedah ${method}.` : language === 'zh' ? `Ujrah 估算使用${method}算法。` : `${method} முறை Ujrah கணக்கு.`;
  }

  const estate = source.match(/^After (RM [\d,.]+) deductions and (RM [\d,.]+) allowed wasiyyah\.$/);
  if (estate) return language === 'bm' ? `Selepas potongan ${estate[1]} dan wasiat dibenarkan ${estate[2]}.` : language === 'zh' ? `扣除 ${estate[1]}，以及允许的遗嘱 ${estate[2]} 之后。` : `${estate[1]} பிடித்தம், ${estate[2]} அனுமதிக்கப்பட்ட Wasiyyah-க்குப் பிறகு.`;

  const yearsMonths = source.match(/^(\d+) years? (?:(\d+) months?)?$/);
  if (yearsMonths) {
    const years = yearsMonths[1];
    const months = yearsMonths[2];
    if (language === 'bm') return `${years} tahun${months ? ` ${months} bulan` : ''}`;
    if (language === 'zh') return `${years} 年${months ? ` ${months} 个月` : ''}`;
    return `${years} ஆண்டு${months ? ` ${months} மாதம்` : ''}`;
  }
  const monthsOnly = source.match(/^(\d+) months?$/);
  if (monthsOnly) return language === 'bm' ? `${monthsOnly[1]} bulan` : language === 'zh' ? `${monthsOnly[1]} 个月` : `${monthsOnly[1]} மாதம்`;
  const shortDuration = source.match(/^(\d+) yr(?: (\d+) mo)?$/);
  if (shortDuration) return language === 'bm' ? `${shortDuration[1]} thn${shortDuration[2] ? ` ${shortDuration[2]} bln` : ''}` : language === 'zh' ? `${shortDuration[1]} 年${shortDuration[2] ? ` ${shortDuration[2]} 个月` : ''}` : `${shortDuration[1]} ஆண்டு${shortDuration[2] ? ` ${shortDuration[2]} மாதம்` : ''}`;
  const shortMonths = source.match(/^(\d+) mo$/);
  if (shortMonths) return language === 'bm' ? `${shortMonths[1]} bln` : language === 'zh' ? `${shortMonths[1]} 个月` : `${shortMonths[1]} மாதம்`;

  const validation = source.match(/^(.+) (must be above 0|cannot be negative|must be below 100%)\.$/);
  if (validation) {
    const label: string = translate(language, validation[1]);
    if (language === 'bm') return validation[2] === 'must be above 0' ? `${label} mesti lebih daripada 0.` : validation[2] === 'cannot be negative' ? `${label} tak boleh negatif.` : `${label} mesti bawah 100%.`;
    if (language === 'zh') return validation[2] === 'must be above 0' ? `${label}必须大于 0。` : validation[2] === 'cannot be negative' ? `${label}不能是负数。` : `${label}必须低于 100%。`;
    return validation[2] === 'must be above 0' ? `${label} 0-க்கு மேல் இருக்க வேண்டும்.` : validation[2] === 'cannot be negative' ? `${label} negative-ஆக இருக்க முடியாது.` : `${label} 100%-க்கு கீழ் இருக்க வேண்டும்.`;
  }
  return null;
}

const dictionaries: Record<Exclude<Language, 'en'>, Record<string, string>> = {
  bm: {
    'Home': 'Utama', 'Calculators': 'Kalkulator', 'Saved': 'Disimpan', 'Settings': 'Tetapan',
    'Main navigation': 'Navigasi utama', 'Go to home': 'Pergi ke utama', 'Open personal profile': 'Buka profil peribadi',
    'Good evening': 'Selamat petang', "Here's where your money stands today.": 'Ini ringkasan duit anda hari ini.',
    'Set up your profile': 'Siapkan profil anda', 'Two minutes unlocks take-home pay and affordability checks everywhere.': 'Dua minit saja untuk lihat gaji bersih dan kemampuan anda.',
    'Create profile': 'Buat profil', 'Monthly snapshot': 'Ringkasan bulanan', 'Take-home pay': 'Gaji bersih', 'DSR used': 'DSR digunakan',
    'Comfortable room for {amount} more before your {percent}% DSR target.': 'Masih ada ruang sekitar {amount} sebelum capai sasaran DSR {percent}%.',
    'Active loans': 'Pinjaman aktif', 'Manage': 'Urus', 'Add loan': 'Tambah pinjaman', 'Track real loan balances': 'Pantau baki pinjaman sebenar',
    'See payoff time, commitments and projected interest.': 'Lihat bila habis bayar, komitmen dan anggaran faedah.', '{count} loan outstanding': '{count} pinjaman aktif', '{count} loans outstanding': '{count} pinjaman aktif', 'per month': 'sebulan',
    'Continue where you left off': 'Sambung dari tadi', 'See all': 'Lihat semua',
    'Pick one - every result is an estimate you can save.': 'Pilih satu - semua hasil ialah anggaran yang boleh disimpan.',
    'Language': 'Bahasa', 'Applies everywhere in the app, right away.': 'Terus digunakan di seluruh aplikasi.',
    'The whole app changes as soon as you pick a language.': 'Seluruh aplikasi terus bertukar bila anda pilih bahasa.',
    'Appearance': 'Paparan', 'Light': 'Cerah', 'Dark': 'Gelap', 'App icon': 'Ikon aplikasi', 'Card background darkness': 'Kegelapan latar kad', 'Theme colour': 'Warna tema',
    'Account': 'Akaun', 'Personal profile': 'Profil peribadi', 'Set up': 'Sudah siap', 'Not set': 'Belum siap', 'Account & cloud sync': 'Akaun & sync awan',
    'Synced': 'Dah sync', 'Syncing': 'Sedang sync', 'Needs attention': 'Perlu semak', 'More': 'Lain-lain', 'Legal & privacy': 'Undang-undang & privasi',
    'Terms and data': 'Terma dan data', 'Remove ads': 'Buang iklan', 'Go ad-free': 'Tanpa iklan', 'About Spectra': 'Tentang Spectra', 'Developed by Spectrality Enterprise': 'Dibangunkan oleh Spectrality Enterprise',
    'Just the essentials - one screen, no rabbit holes.': 'Yang penting saja - semuanya dalam satu skrin.',
    'Estimates in MYR - review official quotes before deciding': 'Anggaran dalam MYR - semak tawaran rasmi sebelum buat keputusan',
    'Important': 'Penting', 'Optional': 'Pilihan', 'Calculate to review the full breakdown': 'Tekan kira untuk lihat pecahan penuh', 'Result': 'Hasil',
    'Calculate': 'Jom kira', 'Recalculate': 'Kira semula', 'Save result': 'Simpan hasil', 'Reset calculator': 'Set semula kalkulator',
    'Full calculation breakdown': 'Pecahan kiraan penuh', 'Breakdown': 'Pecahan', 'Estimated Faraid shares': 'Anggaran bahagian Faraid', 'Planning notes': 'Nota ringkas',
    'Saved scenarios': 'Senario disimpan', 'Compare scenarios side by side before you decide.': 'Bandingkan pilihan sebelah-menyebelah sebelum buat keputusan.',
    'Salary profiles': 'Profil gaji', 'Name and save income scenarios for family members or clients. These stay separate from your personal profile.': 'Simpan contoh pendapatan untuk keluarga atau klien. Ia tidak bercampur dengan profil peribadi anda.',
    'New profile': 'Profil baru', 'Limit reached': 'Dah penuh', 'Loan scenarios': 'Senario pinjaman', '{count}/3 selected': '{count}/3 dipilih',
    'No saved calculations yet.': 'Belum ada kiraan disimpan.', 'Use the bookmark button in any calculator to keep a result here.': 'Tekan ikon simpan dalam kalkulator untuk letak hasil di sini.',
    'Re-save this result to compare it': 'Simpan semula untuk bandingkan', 'Compare selected': 'Bandingkan pilihan', 'View active loans': 'Lihat pinjaman aktif',
    'Side-by-side': 'Sebelah-menyebelah', 'Close comparison': 'Tutup perbandingan', 'Compare scenarios with similar amounts and goals. Lower cost alone does not make a product suitable.': 'Bandingkan pilihan dengan jumlah dan tujuan yang sama. Murah saja belum tentu paling sesuai.',
    'Metric': 'Butiran', 'Monthly payment': 'Bayaran bulanan', 'Total repayment': 'Jumlah bayaran', 'Upfront cash': 'Tunai awal', 'Timeline': 'Tempoh', 'Not cleared': 'Belum habis',
    'Keep real balances and monthly commitments in one place.': 'Simpan baki sebenar dan bayaran bulanan di satu tempat.', 'Active loan summary': 'Ringkasan pinjaman aktif',
    'Total outstanding': 'Jumlah baki', 'Monthly payments': 'Bayaran bulanan', 'Projected interest': 'Anggaran faedah', 'Your loans': 'Pinjaman anda',
    'No active loans yet.': 'Belum ada pinjaman aktif.', 'Add one manually or use the track button beside a saved loan scenario.': 'Tambah sendiri atau tekan ikon pantau pada senario pinjaman yang disimpan.',
    'Track a loan': 'Pantau pinjaman', 'Update loan': 'Kemas kini pinjaman', 'Close loan form': 'Tutup borang pinjaman',
    'Use the latest balance from your bank statement. Spectra estimates the payoff path from these figures.': 'Guna baki terkini daripada penyata bank. Spectra akan anggarkan perjalanan bayaran anda.',
    'Loan name': 'Nama pinjaman', 'e.g. Maybank home loan': 'contoh: Pinjaman rumah Maybank', 'Loan type': 'Jenis pinjaman', 'Outstanding balance': 'Baki tertunggak',
    'Annual rate': 'Kadar tahunan', 'Next payment': 'Bayaran seterusnya', 'Start tracking': 'Mula pantau', 'Save changes': 'Simpan perubahan',
    'Enter a name, positive balance and payment, plus a valid rate.': 'Isi nama, baki dan bayaran yang betul, serta kadar yang sah.',
    'Outstanding': 'Baki', 'Monthly': 'Bulanan', 'Payoff estimate': 'Anggaran habis bayar', 'Future interest': 'Faedah akan datang', 'Over 50 yr': 'Lebih 50 tahun', 'Paid off': 'Dah selesai',
    'Next payment {date}': 'Bayaran seterusnya {date}', 'Payment may not clear this balance within 50 years.': 'Bayaran ini mungkin tak cukup untuk habiskan baki dalam 50 tahun.',
    'Projections are planning estimates. Your lender statement remains the source of truth.': 'Ini cuma anggaran untuk merancang. Penyata bank anda tetap rujukan utama.',
  },
  zh: {
    'Home': '主页', 'Calculators': '计算器', 'Saved': '已保存', 'Settings': '设置', 'Main navigation': '主导航',
    'Go to home': '回到主页', 'Open personal profile': '打开个人资料', 'Good evening': '晚上好', "Here's where your money stands today.": '来看看今天的财务状况。',
    'Set up your profile': '设定个人资料', 'Two minutes unlocks take-home pay and affordability checks everywhere.': '只需两分钟，就能查看到手薪资和负担能力。', 'Create profile': '建立资料',
    'Monthly snapshot': '每月概况', 'Take-home pay': '到手薪资', 'DSR used': '已用 DSR', 'Comfortable room for {amount} more before your {percent}% DSR target.': '距离 {percent}% DSR 目标，大约还有 {amount} 的空间。',
    'Active loans': '正在还的贷款', 'Manage': '管理', 'Add loan': '添加贷款', 'Track real loan balances': '跟进真实贷款余额', 'See payoff time, commitments and projected interest.': '查看还清时间、每月负担和预计利息。',
    '{count} loan outstanding': '{count} 笔贷款', '{count} loans outstanding': '{count} 笔贷款', 'per month': '每月', 'Continue where you left off': '继续上次的进度', 'See all': '查看全部',
    'Pick one - every result is an estimate you can save.': '选一个吧 - 每个估算结果都可以保存。', 'Language': '语言', 'Applies everywhere in the app, right away.': '选好后整个 App 马上切换。', 'The whole app changes as soon as you pick a language.': '一选语言，整个 App 马上切换。',
    'Appearance': '外观', 'Light': '浅色', 'Dark': '深色', 'App icon': 'App 图标', 'Card background darkness': '卡片背景深度', 'Theme colour': '主题颜色',
    'Account': '账户', 'Personal profile': '个人资料', 'Set up': '已设定', 'Not set': '还没设定', 'Account & cloud sync': '账户与云同步', 'Synced': '已同步', 'Syncing': '同步中', 'Needs attention': '需要处理',
    'More': '更多', 'Legal & privacy': '条款与隐私', 'Terms and data': '条款和数据', 'Remove ads': '移除广告', 'Go ad-free': '无广告', 'About Spectra': '关于 Spectra', 'Developed by Spectrality Enterprise': '由 Spectrality Enterprise 开发', 'Just the essentials - one screen, no rabbit holes.': '只放重点，一个页面就搞定。',
    'Estimates in MYR - review official quotes before deciding': '以 MYR 估算 - 决定前记得查对正式报价', 'Important': '重要', 'Optional': '选填', 'Calculate to review the full breakdown': '点击计算，查看完整细节', 'Result': '结果', 'Calculate': '开始算', 'Recalculate': '重新算', 'Save result': '保存结果', 'Reset calculator': '重置计算器',
    'Full calculation breakdown': '完整计算细节', 'Breakdown': '详细项目', 'Estimated Faraid shares': '预计 Faraid 份额', 'Planning notes': '小提醒',
    'Saved scenarios': '已保存方案', 'Compare scenarios side by side before you decide.': '决定前，把几个方案放在一起比较。', 'Salary profiles': '薪资资料', 'New profile': '新资料', 'Limit reached': '已达上限', 'Loan scenarios': '贷款方案', '{count}/3 selected': '已选 {count}/3',
    'No saved calculations yet.': '还没有保存任何计算。', 'Use the bookmark button in any calculator to keep a result here.': '在计算器里点保存，结果就会放在这里。', 'Re-save this result to compare it': '重新保存后就能比较', 'Compare selected': '比较已选方案', 'View active loans': '查看正在还的贷款',
    'Side-by-side': '放在一起看', 'Close comparison': '关闭比较', 'Metric': '项目', 'Monthly payment': '每月还款', 'Total repayment': '总还款', 'Upfront cash': '前期现金', 'Timeline': '时间', 'Not cleared': '还没还清',
    'Keep real balances and monthly commitments in one place.': '把真实余额和每月还款放在一起管。', 'Active loan summary': '贷款概况', 'Total outstanding': '总余额', 'Monthly payments': '每月还款', 'Projected interest': '预计利息', 'Your loans': '你的贷款',
    'No active loans yet.': '还没有正在跟进的贷款。', 'Add one manually or use the track button beside a saved loan scenario.': '可以自己添加，或点已保存方案旁的跟进按钮。', 'Track a loan': '跟进贷款', 'Update loan': '更新贷款', 'Close loan form': '关闭贷款表格',
    'Loan name': '贷款名称', 'e.g. Maybank home loan': '例如：Maybank 房屋贷款', 'Loan type': '贷款类型', 'Outstanding balance': '未还余额', 'Annual rate': '年利率', 'Next payment': '下次还款', 'Start tracking': '开始跟进', 'Save changes': '保存更改',
    'Outstanding': '未还余额', 'Monthly': '每月', 'Payoff estimate': '预计还清', 'Future interest': '之后的利息', 'Over 50 yr': '超过 50 年', 'Paid off': '已还清', 'Next payment {date}': '下次还款 {date}',
    'Projections are planning estimates. Your lender statement remains the source of truth.': '这些只是规划用的估算，最后还是以银行账单为准。',
  },
  ta: {
    'Home': 'முகப்பு', 'Calculators': 'கணக்கிடுகள்', 'Saved': 'சேமித்தவை', 'Settings': 'அமைப்புகள்', 'Main navigation': 'முக்கிய வழிசெலுத்தல்',
    'Go to home': 'முகப்புக்கு போ', 'Open personal profile': 'சுயவிவரத்தைத் திற', 'Good evening': 'மாலை வணக்கம்', "Here's where your money stands today.": 'இன்றைய பண நிலையைப் பார்ப்போம்.',
    'Set up your profile': 'சுயவிவரத்தை அமை', 'Two minutes unlocks take-home pay and affordability checks everywhere.': 'இரண்டு நிமிடத்தில் கையில் வரும் சம்பளம், வாங்கும் திறன் எல்லாம் தெரியும்.', 'Create profile': 'சுயவிவரம் உருவாக்கு',
    'Monthly snapshot': 'மாத சுருக்கம்', 'Take-home pay': 'கையில் வரும் சம்பளம்', 'DSR used': 'பயன்படுத்திய DSR', 'Comfortable room for {amount} more before your {percent}% DSR target.': '{percent}% DSR இலக்குக்கு முன் இன்னும் {amount} அளவு இடம் இருக்கிறது.',
    'Active loans': 'நடப்பு கடன்கள்', 'Manage': 'நிர்வகி', 'Add loan': 'கடன் சேர்', 'Track real loan balances': 'உண்மையான கடன் மீதியைப் பார்', 'See payoff time, commitments and projected interest.': 'எப்போது முடியும், மாத சுமை, வட்டி எல்லாம் பார்.',
    '{count} loan outstanding': '{count} கடன்', '{count} loans outstanding': '{count} கடன்கள்', 'per month': 'மாதத்திற்கு', 'Continue where you left off': 'விட்ட இடத்திலிருந்து தொடர்', 'See all': 'அனைத்தையும் பார்',
    'Pick one - every result is an estimate you can save.': 'ஒன்றைத் தேர்ந்தெடு - எல்லா முடிவையும் சேமிக்கலாம்.', 'Language': 'மொழி', 'Applies everywhere in the app, right away.': 'தேர்ந்ததும் முழு App-ம் மாறும்.', 'The whole app changes as soon as you pick a language.': 'மொழியைத் தேர்ந்ததும் முழு App-ம் மாறும்.',
    'Appearance': 'தோற்றம்', 'Light': 'வெளிச்சம்', 'Dark': 'இருள்', 'App icon': 'App ஐகான்', 'Card background darkness': 'அட்டை பின்னணி இருட்டு', 'Theme colour': 'தீம் நிறம்',
    'Account': 'கணக்கு', 'Personal profile': 'சுயவிவரம்', 'Set up': 'தயார்', 'Not set': 'இன்னும் இல்லை', 'Account & cloud sync': 'கணக்கு & cloud sync', 'Synced': 'Sync ஆகிவிட்டது', 'Syncing': 'Sync ஆகிறது', 'Needs attention': 'கவனம் தேவை',
    'More': 'மேலும்', 'Legal & privacy': 'விதிகள் & தனியுரிமை', 'Terms and data': 'விதிகள் மற்றும் தரவு', 'Remove ads': 'விளம்பரம் நீக்கு', 'Go ad-free': 'விளம்பரம் இல்லாமல்', 'About Spectra': 'Spectra பற்றி', 'Developed by Spectrality Enterprise': 'Spectrality Enterprise உருவாக்கியது',
    'Just the essentials - one screen, no rabbit holes.': 'தேவையானது மட்டும் - ஒரே திரையில்.', 'Estimates in MYR - review official quotes before deciding': 'MYR கணக்கு - முடிவுக்கு முன் அதிகாரப்பூர்வ தொகையைப் பார்', 'Important': 'முக்கியம்', 'Optional': 'விருப்பம்',
    'Calculate to review the full breakdown': 'முழு விவரத்தைப் பார்க்க கணக்கிடு', 'Result': 'முடிவு', 'Calculate': 'கணக்கிடு', 'Recalculate': 'மீண்டும் கணக்கிடு', 'Save result': 'முடிவை சேமி', 'Reset calculator': 'கணக்கிடுவதை மீட்டமை',
    'Full calculation breakdown': 'முழு கணக்கு விவரம்', 'Breakdown': 'விவரம்', 'Estimated Faraid shares': 'மதிப்பிட்ட Faraid பங்குகள்', 'Planning notes': 'சிறு குறிப்புகள்',
    'Saved scenarios': 'சேமித்த திட்டங்கள்', 'Compare scenarios side by side before you decide.': 'முடிவு எடுப்பதற்கு முன் திட்டங்களை ஒன்றாகப் பார்.', 'Salary profiles': 'சம்பள விவரங்கள்', 'New profile': 'புதிய விவரம்', 'Limit reached': 'வரம்பு எட்டிவிட்டது', 'Loan scenarios': 'கடன் திட்டங்கள்', '{count}/3 selected': '{count}/3 தேர்வு',
    'No saved calculations yet.': 'இன்னும் கணக்கு எதுவும் சேமிக்கவில்லை.', 'Use the bookmark button in any calculator to keep a result here.': 'கணக்கிடுவதில் சேமிப்பு பட்டனை அழுத்து.', 'Re-save this result to compare it': 'ஒப்பிட மீண்டும் சேமி', 'Compare selected': 'தேர்வை ஒப்பிடு', 'View active loans': 'நடப்பு கடன்களைப் பார்',
    'Side-by-side': 'பக்கத்துப் பக்கம்', 'Close comparison': 'ஒப்பிடுவதை மூடு', 'Metric': 'விவரம்', 'Monthly payment': 'மாத தவணை', 'Total repayment': 'மொத்த திருப்பிச் செலுத்தல்', 'Upfront cash': 'தொடக்கப் பணம்', 'Timeline': 'காலம்', 'Not cleared': 'முடியவில்லை',
    'Keep real balances and monthly commitments in one place.': 'உண்மையான மீதி, மாத தவணையை ஒரே இடத்தில் பார்.', 'Active loan summary': 'கடன் சுருக்கம்', 'Total outstanding': 'மொத்த மீதி', 'Monthly payments': 'மாத தவணைகள்', 'Projected interest': 'மதிப்பிட்ட வட்டி', 'Your loans': 'உங்கள் கடன்கள்',
    'No active loans yet.': 'இன்னும் நடப்பு கடன் இல்லை.', 'Add one manually or use the track button beside a saved loan scenario.': 'நீங்களே சேருங்கள் அல்லது சேமித்த திட்டத்தில் track பட்டனை அழுத்துங்கள்.', 'Track a loan': 'கடனைப் பார்', 'Update loan': 'கடனை புதுப்பி', 'Close loan form': 'கடன் படிவத்தை மூடு',
    'Loan name': 'கடன் பெயர்', 'e.g. Maybank home loan': 'உதாரணம்: Maybank வீட்டுக் கடன்', 'Loan type': 'கடன் வகை', 'Outstanding balance': 'மீதித் தொகை', 'Annual rate': 'வருட விகிதம்', 'Next payment': 'அடுத்த தவணை', 'Start tracking': 'பார்க்கத் தொடங்கு', 'Save changes': 'மாற்றத்தை சேமி',
    'Outstanding': 'மீதி', 'Monthly': 'மாதம்', 'Payoff estimate': 'முடியும் காலம்', 'Future interest': 'இனிமேல் வட்டி', 'Over 50 yr': '50 ஆண்டுகளுக்கு மேல்', 'Paid off': 'முடிந்தது', 'Next payment {date}': 'அடுத்த தவணை {date}',
    'Projections are planning estimates. Your lender statement remains the source of truth.': 'இது திட்டமிடுவதற்கான கணக்கு மட்டும். வங்கி அறிக்கையே சரியானது.',
  },
};

const financeDictionaries: Record<Exclude<Language, 'en'>, Record<string, string>> = {
  bm: {
    'Add': 'Tambah', 'Take-home': 'Gaji bersih', 'Max loan installment': 'Ansuran maksimum', 'mo': 'bln', 'Close': 'Tutup', 'saved plan': 'pelan disimpan', 'income': 'pendapatan', 'balance': 'baki', 'stamp duty': 'duti setem', 'vehicle': 'kenderaan', 'Flat rate': 'Kadar rata', 'Reducing balance': 'Baki berkurang', 'No extra payment': 'Tiada bayaran tambahan', 'No fee buffer': 'Tiada anggaran yuran', 'Not added': 'Belum ditambah', 'None': 'Tiada', 'None entered': 'Belum diisi',
    'Home Loan': 'Pinjaman Rumah', 'Home': 'Utama', 'Property financing': 'Pembiayaan rumah', 'Installment, upfront cash and full cost estimate': 'Anggaran ansuran, tunai awal dan jumlah kos', 'Installment, upfront cash & full amortization': 'Ansuran, tunai awal dan jadual bayaran penuh',
    'Car Loan': 'Pinjaman Kereta', 'Car': 'Kereta', 'Hire purchase estimate': 'Anggaran sewa beli', 'Malaysia flat-rate hire purchase planning': 'Kiraan mudah sewa beli kadar rata Malaysia', 'Hire purchase flat-rate installment': 'Ansuran sewa beli kadar rata',
    'Personal Loan': 'Pinjaman Peribadi', 'Personal': 'Peribadi', 'Personal financing': 'Pembiayaan peribadi', 'Compare reducing-balance and flat-rate repayments': 'Bandingkan bayaran baki berkurang dengan kadar rata', 'Reducing-balance or flat-rate repayment': 'Bayaran baki berkurang atau kadar rata',
    'Credit Card Payoff': 'Bayar Habis Kad Kredit', 'Card': 'Kad', 'Credit card payoff': 'Bayar habis kad kredit', 'See payoff time and the cost of minimum payments': 'Lihat bila boleh habis dan kos jika bayar minimum', 'Payoff timeline & minimum-payment cost': 'Tempoh habis bayar & kos bayaran minimum',
    'PTPTN Loan': 'Pinjaman PTPTN', 'PTPTN': 'PTPTN', 'PTPTN repayment': 'Bayaran balik PTPTN', 'Education loan repayment and Ujrah planning': 'Rancang bayaran pinjaman pendidikan dan Ujrah', 'Education repayment, discount-aware': 'Rancang bayaran pendidikan dengan mudah',
    'Faraid Inheritance': 'Pusaka Faraid', 'Faraid': 'Faraid', 'Faraid inheritance estimate': 'Anggaran pusaka Faraid', 'Islamic inheritance shares for core direct heirs': 'Anggaran bahagian waris terdekat', 'Islamic estate share estimate': 'Anggaran bahagian pusaka Islam',
    'Loan basics': 'Asas pinjaman', 'Property price': 'Harga rumah', 'Down payment': 'Bayaran muka', 'Interest rate': 'Kadar faedah', 'Tenure': 'Tempoh',
    'Buyer & property status': 'Status pembeli & rumah', 'Buyer status': 'Status pembeli', 'Citizen': 'Warganegara', 'Foreign': 'Warga asing', 'Property type': 'Jenis rumah', 'Subsale': 'Subsale', 'New project': 'Projek baru', 'First residential home': 'Rumah kediaman pertama',
    'Affordability check': 'Semak kemampuan', 'Your saved profile is used automatically. Adjust these values for this estimate only.': 'Profil anda digunakan automatik. Ubah angka ini untuk kiraan kali ini saja.', 'Monthly gross income': 'Gaji kasar bulanan', 'Existing commitments': 'Komitmen sedia ada', 'Target DSR': 'Sasaran DSR',
    'Vehicle & financing': 'Kereta & pembiayaan', 'Vehicle price': 'Harga kereta', 'Vehicle details': 'Butiran kereta', 'Vehicle type': 'Jenis kereta', 'New': 'Baru', 'Used': 'Terpakai', 'Upfront costs': 'Kos awal', 'Upfront fee buffer': 'Anggaran yuran awal',
    'Loan amount': 'Jumlah pinjaman', 'Interest method': 'Cara kira faedah', 'Method': 'Kaedah', 'Reducing': 'Baki berkurang', 'Flat': 'Kadar rata', 'Fees & stamp duty': 'Yuran & duti setem', 'Upfront fees': 'Yuran awal', 'Stamp duty rate': 'Kadar duti setem',
    'Balance & payment': 'Baki & bayaran', 'Finance charge': 'Caj kewangan', 'Minimum-payment terms': 'Syarat bayaran minimum', 'Minimum payment': 'Bayaran minimum', 'Minimum floor': 'Minimum terendah', 'New spending': 'Belanja baru', 'Monthly new spending': 'Belanja baru bulanan',
    'Repayment basics': 'Asas bayaran balik', 'Ujrah rate': 'Kadar Ujrah', 'years': 'tahun', 'Charge method': 'Cara kira caj', 'Pay faster': 'Bayar lebih cepat', 'Extra monthly payment': 'Bayaran tambahan bulanan', 'Total Ujrah': 'Jumlah Ujrah',
    'Estate value': 'Nilai pusaka', 'Gross estate': 'Jumlah pusaka kasar', 'Debts & expenses': 'Hutang & belanja', 'Wasiyyah': 'Wasiat', 'Spouse & children': 'Pasangan & anak', 'Deceased': 'Si mati', 'Male': 'Lelaki', 'Female': 'Perempuan', 'Wife / wives': 'Isteri', 'Husband survived': 'Suami masih hidup', 'Sons': 'Anak lelaki', 'Daughters': 'Anak perempuan', 'Parents': 'Ibu bapa', 'Father survived': 'Bapa masih hidup', 'Mother survived': 'Ibu masih hidup', 'Heir groups': 'Kumpulan waris',
    'Estimated monthly installment': 'Anggaran ansuran bulanan', 'Estimated monthly payment': 'Anggaran bayaran bulanan', 'Total interest': 'Jumlah faedah', 'Total interest/profit': 'Jumlah faedah/keuntungan', 'Effective rate est.': 'Anggaran kadar efektif', 'Amount financed': 'Jumlah dibiayai', 'DSR after loan': 'DSR selepas pinjaman',
    'Transfer stamp duty': 'Duti setem pindah milik', 'Loan agreement duty': 'Duti perjanjian pinjaman', 'Professional fee estimate': 'Anggaran yuran profesional', 'Planning DSR target': 'Sasaran DSR', 'Stamp duty est.': 'Anggaran duti setem', 'Total cost': 'Jumlah kos', 'Principal': 'Jumlah pokok',
    'Estimated payoff time': 'Anggaran masa habis bayar', 'Payment may not clear balance': 'Bayaran mungkin tak cukup', 'Fixed-payment interest': 'Faedah bayaran tetap', 'Minimum-only time': 'Tempoh jika bayar minimum', 'Minimum-only interest': 'Faedah jika bayar minimum', 'First minimum payment': 'Bayaran minimum pertama',
    'Planned monthly repayment': 'Bayaran bulanan dirancang', 'Scheduled payment': 'Bayaran dijadualkan', 'Total Ujrah est.': 'Anggaran jumlah Ujrah', 'Payoff time': 'Masa habis bayar',
    'Net distributable estate': 'Pusaka bersih untuk dibahagi', 'Wasiyyah used': 'Wasiat digunakan', 'Total distributed': 'Jumlah dibahagi',
    'This is a planning estimate only. Confirm final shares with a certified Faraid officer or the Syariah court.': 'Ini anggaran untuk merancang saja. Semak bahagian akhir dengan pegawai Faraid bertauliah atau Mahkamah Syariah.',
    'Check the input values.': 'Semak semula angka yang dimasukkan.', 'Heir counts cannot be negative.': 'Bilangan waris tak boleh negatif.', 'Wife count cannot exceed 4.': 'Bilangan isteri tak boleh lebih daripada 4.',
    'Payment may not clear this balance within 50 years.': 'Bayaran ini mungkin tak cukup untuk habiskan baki dalam 50 tahun.',
    'Home loan': 'Pinjaman rumah', 'Car loan': 'Pinjaman kereta', 'Personal loan': 'Pinjaman peribadi', 'Credit card': 'Kad kredit', 'Other financing': 'Pembiayaan lain',
    'Use the latest balance from your bank statement. Spectra estimates the payoff path from these figures.': 'Guna baki terbaru dalam penyata bank. Spectra akan anggarkan perjalanan bayaran daripada angka ini.',
    'Compare scenarios with similar amounts and goals. Lower cost alone does not make a product suitable.': 'Bandingkan pelan dengan jumlah dan tujuan yang sama. Yang paling murah belum tentu paling sesuai.',
    'Name and save income scenarios for family members or clients. These stay separate from your personal profile.': 'Simpan contoh gaji untuk keluarga atau klien. Ia tak bercampur dengan profil peribadi anda.',
    'Father': 'Bapa', 'Mother': 'Ibu', 'Wife': 'Isteri', 'Wives': 'Isteri', 'Husband': 'Suami', 'Son': 'Anak lelaki', 'Daughter': 'Anak perempuan', 'Undistributed residue': 'Baki belum dibahagi',
    'Wife/wives receive 1/8 when children exist.': 'Isteri dapat 1/8 bila ada anak.', 'Wife/wives receive 1/4 when no children exist.': 'Isteri dapat 1/4 bila tiada anak.', 'Husband receives 1/4 when children exist.': 'Suami dapat 1/4 bila ada anak.', 'Husband receives 1/2 when no children exist.': 'Suami dapat 1/2 bila tiada anak.', 'Mother receives 1/6 when children exist.': 'Ibu dapat 1/6 bila ada anak.', 'Mother receives 1/3 of the remainder after spouse.': 'Ibu dapat 1/3 daripada baki selepas bahagian pasangan.', 'Mother receives 1/3 when no children are entered.': 'Ibu dapat 1/3 bila tiada anak.',
    'Father receives 1/6 when sons exist.': 'Bapa dapat 1/6 bila ada anak lelaki.', 'Father receives 1/6 plus residue when only daughters exist.': 'Bapa dapat 1/6 dan baki bila hanya ada anak perempuan.', 'One daughter receives 1/2 when no sons exist.': 'Seorang anak perempuan dapat 1/2 bila tiada anak lelaki.', 'Two or more daughters share 2/3 when no sons exist.': 'Dua atau lebih anak perempuan berkongsi 2/3 bila tiada anak lelaki.', 'Children receive residue, with each son taking the share of two daughters.': 'Baki dibahagi kepada anak; setiap anak lelaki dapat dua bahagian anak perempuan.',
    'Father also receives residue after daughter fixed share.': 'Bapa juga dapat baki selepas bahagian tetap anak perempuan.', 'Father receives residue after spouse/mother fixed shares.': 'Bapa dapat baki selepas bahagian tetap pasangan dan ibu.', 'No supported residuary heir was entered. Refer this balance for faraid review.': 'Tiada waris baki yang disokong dimasukkan. Rujuk baki ini untuk semakan Faraid.', 'Adjusted proportionally because fixed shares exceed the estate.': 'Bahagian dilaraskan sebab jumlah bahagian tetap melebihi pusaka.', 'Residue returned proportionally by radd estimate.': 'Baki dipulangkan secara berkadar melalui anggaran radd.',
    'Covers spouse, parents, sons, and daughters only.': 'Kiraan ini hanya meliputi pasangan, ibu bapa, anak lelaki dan anak perempuan.', 'Confirm entitled heirs and shares with the Syariah Court or a qualified faraid advisor.': 'Sahkan waris dan bahagian dengan Mahkamah Syariah atau penasihat Faraid bertauliah.', 'Awl applied: fixed shares exceeded 100%.': 'Awl digunakan kerana bahagian tetap melebihi 100%.', 'Radd estimate applied to supported non-spouse fixed heirs.': 'Anggaran radd digunakan untuk waris tetap yang disokong selain pasangan.', 'Wasiyyah was capped at one third after debts and expenses.': 'Wasiat dihadkan kepada satu pertiga selepas hutang dan belanja.',
  },
  zh: {
    'Add': '添加', 'Take-home': '到手薪资', 'Max loan installment': '最高贷款月供', 'mo': '月', 'Close': '关闭', 'saved plan': '已保存方案', 'income': '收入', 'balance': '余额', 'stamp duty': '印花税', 'vehicle': '汽车', 'Flat rate': '平息', 'Reducing balance': '余额递减', 'No extra payment': '没有多还', 'No fee buffer': '没有费用预算', 'Not added': '还没填', 'None': '没有', 'None entered': '还没填',
    'Home Loan': '房屋贷款', 'Property financing': '房屋贷款', 'Installment, upfront cash and full cost estimate': '估算月供、前期现金和总成本', 'Installment, upfront cash & full amortization': '月供、前期现金和完整还款表',
    'Car Loan': '汽车贷款', 'Car': '汽车', 'Hire purchase estimate': '汽车贷款估算', 'Malaysia flat-rate hire purchase planning': '马来西亚平息汽车贷款估算', 'Hire purchase flat-rate installment': '平息汽车贷款月供',
    'Personal Loan': '个人贷款', 'Personal': '个人', 'Personal financing': '个人贷款', 'Compare reducing-balance and flat-rate repayments': '比较余额递减和平息还款', 'Reducing-balance or flat-rate repayment': '余额递减或平息还款',
    'Credit Card Payoff': '还清信用卡', 'Card': '信用卡', 'Credit card payoff': '还清信用卡', 'See payoff time and the cost of minimum payments': '看看多久能还清，只还最低会多花多少', 'Payoff timeline & minimum-payment cost': '还清时间与最低还款成本',
    'PTPTN Loan': 'PTPTN 贷款', 'PTPTN repayment': 'PTPTN 还款', 'Education loan repayment and Ujrah planning': '教育贷款和 Ujrah 还款规划', 'Education repayment, discount-aware': '简单规划教育贷款',
    'Faraid Inheritance': 'Faraid 遗产', 'Faraid inheritance estimate': 'Faraid 遗产估算', 'Islamic inheritance shares for core direct heirs': '估算主要直系继承人份额', 'Islamic estate share estimate': '伊斯兰遗产份额估算',
    'Loan basics': '贷款基本资料', 'Property price': '房价', 'Down payment': '首付', 'Interest rate': '利率', 'Tenure': '期限', 'Buyer & property status': '买家与房屋资料', 'Buyer status': '买家身份', 'Citizen': '公民', 'Foreign': '外国人', 'Property type': '房屋类型', 'Subsale': '二手房', 'New project': '新项目', 'First residential home': '第一套住宅',
    'Affordability check': '负担能力检查', 'Your saved profile is used automatically. Adjust these values for this estimate only.': '会自动用你的资料。这里改的数字只影响这次估算。', 'Monthly gross income': '每月税前收入', 'Existing commitments': '现有每月负担', 'Target DSR': 'DSR 目标',
    'Vehicle & financing': '汽车与贷款', 'Vehicle price': '车价', 'Vehicle details': '汽车资料', 'Vehicle type': '汽车类型', 'New': '新车', 'Used': '二手车', 'Upfront costs': '前期费用', 'Upfront fee buffer': '前期费用预算',
    'Loan amount': '贷款金额', 'Interest method': '利息算法', 'Method': '算法', 'Reducing': '余额递减', 'Flat': '平息', 'Fees & stamp duty': '费用与印花税', 'Upfront fees': '前期费用', 'Stamp duty rate': '印花税率',
    'Balance & payment': '余额与还款', 'Finance charge': '财务费率', 'Minimum-payment terms': '最低还款设定', 'Minimum payment': '最低还款', 'Minimum floor': '最低金额', 'New spending': '新消费', 'Monthly new spending': '每月新消费',
    'Repayment basics': '还款基本资料', 'Ujrah rate': 'Ujrah 费率', 'years': '年', 'Charge method': '费用算法', 'Pay faster': '更快还清', 'Extra monthly payment': '每月多还', 'Total Ujrah': 'Ujrah 总额',
    'Estate value': '遗产价值', 'Gross estate': '遗产总额', 'Debts & expenses': '债务与费用', 'Wasiyyah': '遗嘱', 'Spouse & children': '配偶与子女', 'Deceased': '逝者', 'Male': '男', 'Female': '女', 'Wife / wives': '妻子', 'Husband survived': '丈夫在世', 'Sons': '儿子', 'Daughters': '女儿', 'Parents': '父母', 'Father survived': '父亲在世', 'Mother survived': '母亲在世', 'Heir groups': '继承人类别',
    'Estimated monthly installment': '预计每月供款', 'Estimated monthly payment': '预计每月还款', 'Total interest': '总利息', 'Total interest/profit': '总利息/利润', 'Effective rate est.': '预计实际利率', 'Amount financed': '贷款金额', 'DSR after loan': '贷款后 DSR', 'Total cost': '总成本', 'Principal': '本金',
    'Estimated payoff time': '预计还清时间', 'Payment may not clear balance': '还款可能不够', 'Fixed-payment interest': '固定还款利息', 'Minimum-only time': '只还最低所需时间', 'Minimum-only interest': '只还最低的利息', 'First minimum payment': '第一期最低还款',
    'Planned monthly repayment': '计划每月还款', 'Scheduled payment': '原定还款', 'Total Ujrah est.': '预计 Ujrah 总额', 'Payoff time': '还清时间', 'Net distributable estate': '可分配遗产净额', 'Wasiyyah used': '已用遗嘱金额', 'Total distributed': '已分配总额',
    'This is a planning estimate only. Confirm final shares with a certified Faraid officer or the Syariah court.': '这只是规划用的估算。最终份额请和认证 Faraid 官员或伊斯兰法庭确认。',
    'Check the input values.': '再检查一下输入的数字。', 'Heir counts cannot be negative.': '继承人人数不能是负数。', 'Wife count cannot exceed 4.': '妻子人数不能超过 4 人。',
    'Home loan': '房屋贷款', 'Car loan': '汽车贷款', 'Personal loan': '个人贷款', 'Credit card': '信用卡', 'Other financing': '其他贷款',
    'Use the latest balance from your bank statement. Spectra estimates the payoff path from these figures.': '用银行账单上的最新余额。Spectra 会用这些数字估算还款进度。',
    'Compare scenarios with similar amounts and goals. Lower cost alone does not make a product suitable.': '最好比较金额和目标相近的方案。最便宜不一定就最适合。',
    'Name and save income scenarios for family members or clients. These stay separate from your personal profile.': '可以为家人或客户保存不同收入方案，不会和你的个人资料混在一起。',
    'Father': '父亲', 'Mother': '母亲', 'Wife': '妻子', 'Wives': '妻子', 'Husband': '丈夫', 'Son': '儿子', 'Daughter': '女儿', 'Undistributed residue': '未分配余额',
    'Wife/wives receive 1/8 when children exist.': '有子女时，妻子分到 1/8。', 'Wife/wives receive 1/4 when no children exist.': '没有子女时，妻子分到 1/4。', 'Husband receives 1/4 when children exist.': '有子女时，丈夫分到 1/4。', 'Husband receives 1/2 when no children exist.': '没有子女时，丈夫分到 1/2。', 'Mother receives 1/6 when children exist.': '有子女时，母亲分到 1/6。', 'Mother receives 1/3 of the remainder after spouse.': '配偶分配后，母亲得到余额的 1/3。', 'Mother receives 1/3 when no children are entered.': '没有子女时，母亲分到 1/3。',
    'Father receives 1/6 when sons exist.': '有儿子时，父亲分到 1/6。', 'Father receives 1/6 plus residue when only daughters exist.': '只有女儿时，父亲得到 1/6 加余额。', 'One daughter receives 1/2 when no sons exist.': '没有儿子时，一名女儿分到 1/2。', 'Two or more daughters share 2/3 when no sons exist.': '没有儿子时，两名或以上女儿共享 2/3。', 'Children receive residue, with each son taking the share of two daughters.': '余额分给子女，每名儿子得到两名女儿的份额。',
    'Father also receives residue after daughter fixed share.': '女儿固定份额分配后，父亲也得到余额。', 'Father receives residue after spouse/mother fixed shares.': '配偶和母亲固定份额分配后，父亲得到余额。', 'No supported residuary heir was entered. Refer this balance for faraid review.': '没有填入系统支持的余分继承人，请把这笔余额交给 Faraid 专业人士审核。', 'Adjusted proportionally because fixed shares exceed the estate.': '固定份额超过遗产，因此按比例调整。', 'Residue returned proportionally by radd estimate.': '余额按 radd 估算比例返还。',
    'Covers spouse, parents, sons, and daughters only.': '这个计算只包括配偶、父母、儿子和女儿。', 'Confirm entitled heirs and shares with the Syariah Court or a qualified faraid advisor.': '请和伊斯兰法庭或合格 Faraid 顾问确认继承人与最终份额。', 'Awl applied: fixed shares exceeded 100%.': '已应用 Awl，因为固定份额超过 100%。', 'Radd estimate applied to supported non-spouse fixed heirs.': '已对支持的非配偶固定继承人应用 radd 估算。', 'Wasiyyah was capped at one third after debts and expenses.': '扣除债务和费用后，遗嘱上限为三分之一。',
  },
  ta: {
    'Add': 'சேர்', 'Take-home': 'கையில் வரும் சம்பளம்', 'Max loan installment': 'அதிகபட்ச கடன் தவணை', 'mo': 'மாதம்', 'Close': 'மூடு', 'saved plan': 'சேமித்த திட்டம்', 'income': 'வருமானம்', 'balance': 'மீதி', 'stamp duty': 'stamp duty', 'vehicle': 'கார்', 'Flat rate': 'நிலையான வட்டி', 'Reducing balance': 'குறையும் மீதி', 'No extra payment': 'கூடுதல் பணம் இல்லை', 'No fee buffer': 'கட்டண கணக்கு இல்லை', 'Not added': 'இன்னும் சேர்க்கவில்லை', 'None': 'எதுவும் இல்லை', 'None entered': 'இன்னும் இல்லை',
    'Home Loan': 'வீட்டுக் கடன்', 'Property financing': 'வீட்டு நிதி', 'Installment, upfront cash and full cost estimate': 'தவணை, தொடக்கப் பணம், மொத்தச் செலவு கணக்கு', 'Installment, upfront cash & full amortization': 'தவணை, தொடக்கப் பணம், முழு செலுத்தல் பட்டியல்',
    'Car Loan': 'கார் கடன்', 'Car': 'கார்', 'Hire purchase estimate': 'கார் கடன் கணக்கு', 'Malaysia flat-rate hire purchase planning': 'மலேசிய நிலையான வட்டி கார் கடன் கணக்கு', 'Hire purchase flat-rate installment': 'நிலையான வட்டி கார் தவணை',
    'Personal Loan': 'தனிநபர் கடன்', 'Personal': 'தனிநபர்', 'Personal financing': 'தனிநபர் நிதி', 'Compare reducing-balance and flat-rate repayments': 'குறையும் மீதி, நிலையான வட்டி இரண்டையும் ஒப்பிடு', 'Reducing-balance or flat-rate repayment': 'குறையும் மீதி அல்லது நிலையான வட்டி',
    'Credit Card Payoff': 'கிரெடிட் கார்டை முடி', 'Card': 'கார்டு', 'Credit card payoff': 'கிரெடிட் கார்டை முடி', 'See payoff time and the cost of minimum payments': 'எப்போது முடியும், minimum கட்டினால் எவ்வளவு செலவாகும் என்று பார்', 'Payoff timeline & minimum-payment cost': 'முடியும் காலம் & minimum செலவு',
    'PTPTN Loan': 'PTPTN கடன்', 'PTPTN repayment': 'PTPTN திருப்பிச் செலுத்தல்', 'Education loan repayment and Ujrah planning': 'கல்விக் கடன், Ujrah திட்டமிடல்', 'Education repayment, discount-aware': 'கல்விக் கடனை எளிதாகத் திட்டமிடு',
    'Faraid Inheritance': 'Faraid பரம்பரை', 'Faraid inheritance estimate': 'Faraid பங்கு கணக்கு', 'Islamic inheritance shares for core direct heirs': 'முக்கிய நேரடி வாரிசுகளின் பங்கு', 'Islamic estate share estimate': 'இஸ்லாமிய பங்கு கணக்கு',
    'Loan basics': 'கடன் அடிப்படை', 'Property price': 'வீட்டு விலை', 'Down payment': 'முன்பணம்', 'Interest rate': 'வட்டி விகிதம்', 'Tenure': 'காலம்', 'Buyer & property status': 'வாங்குபவர் & வீட்டு நிலை', 'Buyer status': 'வாங்குபவர் நிலை', 'Citizen': 'குடிமகன்', 'Foreign': 'வெளிநாட்டவர்', 'Property type': 'வீட்டு வகை', 'Subsale': 'மறுவிற்பனை', 'New project': 'புதிய திட்டம்', 'First residential home': 'முதல் வீடு',
    'Affordability check': 'வாங்க முடியுமா?', 'Your saved profile is used automatically. Adjust these values for this estimate only.': 'உங்கள் சுயவிவரம் தானாகப் பயன்படும். இந்தக் கணக்குக்கு மட்டும் இங்கே மாற்றுங்கள்.', 'Monthly gross income': 'மாத மொத்த வருமானம்', 'Existing commitments': 'ஏற்கனவே உள்ள மாத சுமை', 'Target DSR': 'DSR இலக்கு',
    'Vehicle & financing': 'கார் & நிதி', 'Vehicle price': 'கார் விலை', 'Vehicle details': 'கார் விவரம்', 'Vehicle type': 'கார் வகை', 'New': 'புதிய', 'Used': 'பயன்படுத்திய', 'Upfront costs': 'தொடக்கச் செலவு', 'Upfront fee buffer': 'தொடக்க கட்டண கணக்கு',
    'Loan amount': 'கடன் தொகை', 'Interest method': 'வட்டி முறை', 'Method': 'முறை', 'Reducing': 'குறையும் மீதி', 'Flat': 'நிலையான', 'Fees & stamp duty': 'கட்டணம் & stamp duty', 'Upfront fees': 'தொடக்க கட்டணம்', 'Stamp duty rate': 'Stamp duty விகிதம்',
    'Balance & payment': 'மீதி & பணம்', 'Finance charge': 'நிதிக் கட்டணம்', 'Minimum-payment terms': 'குறைந்தபட்ச பணம்', 'Minimum payment': 'குறைந்தபட்ச பணம்', 'Minimum floor': 'மிகக் குறைந்த தொகை', 'New spending': 'புதிய செலவு', 'Monthly new spending': 'மாத புதிய செலவு',
    'Repayment basics': 'திருப்பிச் செலுத்தும் அடிப்படை', 'Ujrah rate': 'Ujrah விகிதம்', 'years': 'ஆண்டுகள்', 'Charge method': 'கட்டண முறை', 'Pay faster': 'விரைவாக முடி', 'Extra monthly payment': 'மாத கூடுதல் பணம்', 'Total Ujrah': 'மொத்த Ujrah',
    'Estate value': 'சொத்து மதிப்பு', 'Gross estate': 'மொத்த சொத்து', 'Debts & expenses': 'கடன் & செலவு', 'Wasiyyah': 'Wasiyyah', 'Spouse & children': 'துணை & பிள்ளைகள்', 'Deceased': 'மறைந்தவர்', 'Male': 'ஆண்', 'Female': 'பெண்', 'Wife / wives': 'மனைவி', 'Husband survived': 'கணவர் உயிருடன்', 'Sons': 'மகன்கள்', 'Daughters': 'மகள்கள்', 'Parents': 'பெற்றோர்', 'Father survived': 'தந்தை உயிருடன்', 'Mother survived': 'தாய் உயிருடன்', 'Heir groups': 'வாரிசு வகைகள்',
    'Estimated monthly installment': 'மாத தவணை கணக்கு', 'Estimated monthly payment': 'மாத பணம் கணக்கு', 'Total interest': 'மொத்த வட்டி', 'Total interest/profit': 'மொத்த வட்டி/லாபம்', 'Effective rate est.': 'உண்மை விகித கணக்கு', 'Amount financed': 'கடன் தொகை', 'DSR after loan': 'கடனுக்குப் பிறகு DSR', 'Total cost': 'மொத்தச் செலவு', 'Principal': 'முதல் தொகை',
    'Estimated payoff time': 'முடியும் கால கணக்கு', 'Payment may not clear balance': 'பணம் போதாமல் இருக்கலாம்', 'Fixed-payment interest': 'நிலையான பணத்தின் வட்டி', 'Minimum-only time': 'Minimum மட்டும் கட்டும் காலம்', 'Minimum-only interest': 'Minimum மட்டும் கட்டினால் வட்டி', 'First minimum payment': 'முதல் minimum பணம்',
    'Planned monthly repayment': 'திட்டமிட்ட மாத பணம்', 'Scheduled payment': 'நிர்ணயித்த பணம்', 'Total Ujrah est.': 'மொத்த Ujrah கணக்கு', 'Payoff time': 'முடியும் காலம்', 'Net distributable estate': 'பங்கிடும் நிகர சொத்து', 'Wasiyyah used': 'பயன்படுத்திய Wasiyyah', 'Total distributed': 'மொத்தம் பங்கிட்டது',
    'This is a planning estimate only. Confirm final shares with a certified Faraid officer or the Syariah court.': 'இது திட்டமிடுவதற்கான கணக்கு மட்டும். இறுதிப் பங்கை Faraid அதிகாரி அல்லது Syariah நீதிமன்றத்தில் உறுதி செய்யுங்கள்.',
    'Check the input values.': 'போட்ட எண்களை மீண்டும் பாருங்கள்.', 'Heir counts cannot be negative.': 'வாரிசு எண்ணிக்கை negative-ஆக இருக்க முடியாது.', 'Wife count cannot exceed 4.': 'மனைவி எண்ணிக்கை 4-க்கு மேல் இருக்க முடியாது.',
    'Home loan': 'வீட்டுக் கடன்', 'Car loan': 'கார் கடன்', 'Personal loan': 'தனிநபர் கடன்', 'Credit card': 'கிரெடிட் கார்டு', 'Other financing': 'மற்ற கடன்',
    'Use the latest balance from your bank statement. Spectra estimates the payoff path from these figures.': 'வங்கி அறிக்கையில் உள்ள புதிய மீதியைப் போடுங்கள். Spectra அதை வைத்து எப்போது முடியும் என்று கணக்கிடும்.',
    'Compare scenarios with similar amounts and goals. Lower cost alone does not make a product suitable.': 'ஒரே போன்ற தொகை, நோக்கம் உள்ள திட்டங்களை ஒப்பிடுங்கள். விலை குறைவாக இருப்பது மட்டும் போதாது.',
    'Name and save income scenarios for family members or clients. These stay separate from your personal profile.': 'குடும்பம் அல்லது வாடிக்கையாளர்களுக்காக சம்பள திட்டங்களை சேமிக்கலாம். அவை உங்கள் சுயவிவரத்தோடு கலக்காது.',
    'Father': 'தந்தை', 'Mother': 'தாய்', 'Wife': 'மனைவி', 'Wives': 'மனைவிகள்', 'Husband': 'கணவர்', 'Son': 'மகன்', 'Daughter': 'மகள்', 'Undistributed residue': 'பகிராத மீதி',
    'Wife/wives receive 1/8 when children exist.': 'பிள்ளைகள் இருந்தால் மனைவிக்கு 1/8 பங்கு.', 'Wife/wives receive 1/4 when no children exist.': 'பிள்ளைகள் இல்லையெனில் மனைவிக்கு 1/4 பங்கு.', 'Husband receives 1/4 when children exist.': 'பிள்ளைகள் இருந்தால் கணவருக்கு 1/4 பங்கு.', 'Husband receives 1/2 when no children exist.': 'பிள்ளைகள் இல்லையெனில் கணவருக்கு 1/2 பங்கு.', 'Mother receives 1/6 when children exist.': 'பிள்ளைகள் இருந்தால் தாய்க்கு 1/6 பங்கு.', 'Mother receives 1/3 of the remainder after spouse.': 'துணையின் பங்குக்குப் பிறகு மீதியில் 1/3 தாய்க்கு.', 'Mother receives 1/3 when no children are entered.': 'பிள்ளைகள் இல்லையெனில் தாய்க்கு 1/3 பங்கு.',
    'Father receives 1/6 when sons exist.': 'மகன்கள் இருந்தால் தந்தைக்கு 1/6 பங்கு.', 'Father receives 1/6 plus residue when only daughters exist.': 'மகள்கள் மட்டும் இருந்தால் தந்தைக்கு 1/6 மற்றும் மீதி.', 'One daughter receives 1/2 when no sons exist.': 'மகன் இல்லாமல் ஒரு மகள் இருந்தால் அவளுக்கு 1/2.', 'Two or more daughters share 2/3 when no sons exist.': 'மகன் இல்லாமல் இரண்டு அல்லது அதிக மகள்கள் இருந்தால் 2/3 பகிர்வார்கள்.', 'Children receive residue, with each son taking the share of two daughters.': 'மீதியை பிள்ளைகள் பகிர்வார்கள்; ஒரு மகனுக்கு இரண்டு மகள்களின் பங்கு.',
    'Father also receives residue after daughter fixed share.': 'மகளின் நிலையான பங்குக்குப் பிறகு தந்தைக்கு மீதியும் கிடைக்கும்.', 'Father receives residue after spouse/mother fixed shares.': 'துணை மற்றும் தாயின் நிலையான பங்குக்குப் பிறகு தந்தைக்கு மீதி கிடைக்கும்.', 'No supported residuary heir was entered. Refer this balance for faraid review.': 'ஆதரிக்கப்படும் மீதி வாரிசு யாரும் இல்லை. இந்த மீதியை Faraid நிபுணரிடம் சரிபார்க்கவும்.', 'Adjusted proportionally because fixed shares exceed the estate.': 'நிலையான பங்குகள் சொத்தைவிட அதிகம் என்பதால் விகிதப்படி மாற்றப்பட்டது.', 'Residue returned proportionally by radd estimate.': 'Radd கணக்குப்படி மீதி விகிதமாகத் திருப்பப்பட்டது.',
    'Covers spouse, parents, sons, and daughters only.': 'இந்தக் கணக்கு துணை, பெற்றோர், மகன், மகள் மட்டும் உள்ளடக்கும்.', 'Confirm entitled heirs and shares with the Syariah Court or a qualified faraid advisor.': 'வாரிசுகளையும் இறுதிப் பங்கையும் Syariah நீதிமன்றம் அல்லது தகுதியான Faraid ஆலோசகரிடம் உறுதி செய்யுங்கள்.', 'Awl applied: fixed shares exceeded 100%.': 'நிலையான பங்குகள் 100%-ஐ கடந்ததால் Awl பயன்படுத்தப்பட்டது.', 'Radd estimate applied to supported non-spouse fixed heirs.': 'துணை அல்லாத ஆதரிக்கப்படும் நிலையான வாரிசுகளுக்கு Radd கணக்கு பயன்படுத்தப்பட்டது.', 'Wasiyyah was capped at one third after debts and expenses.': 'கடன் மற்றும் செலவுக்குப் பிறகு Wasiyyah மூன்றில் ஒன்றாக வரம்பிடப்பட்டது.',
  },
};

const uiDictionaries: Record<Exclude<Language, 'en'>, Record<string, string>> = {
  bm: {
    'Set it once - every calculator can use it to check what fits your budget.': 'Isi sekali saja - semua kalkulator boleh guna untuk semak bajet anda.', 'Income & deductions': 'Pendapatan & potongan', 'Gross monthly salary': 'Gaji kasar bulanan', 'EPF rate': 'Kadar EPF', 'PCB / tax': 'PCB / cukai', 'SOCSO and EIS are estimated automatically for this planning view.': 'SOCSO dan EIS dikira automatik untuk anggaran ini.',
    'Cashflow plan': 'Pelan aliran tunai', 'Living expenses': 'Belanja hidup', 'Investment view': 'Pandangan pelaburan', 'Not configured': 'Belum disiapkan', 'For rental or income-producing assets. Cashflow estimates are not investment advice.': 'Untuk aset sewa atau aset yang jana pendapatan. Anggaran aliran tunai bukan nasihat pelaburan.', 'Investment income fields will arrive with property scenario comparison.': 'Butiran pendapatan pelaburan akan ditambah bersama perbandingan hartanah.', 'Room left': 'Baki ruang', 'Profile saved': 'Profil dah disimpan', 'Save profile': 'Simpan profil',
    'New salary profile': 'Profil gaji baru', '{count} of 15 slots used - name it for a family member or client.': '{count} daripada 15 ruang digunakan - namakan untuk keluarga atau klien.', 'Profile name': 'Nama profil', 'e.g. Wife, Mum, Client - Aiman': 'contoh: Isteri, Ibu, Klien - Aiman', 'Quick label (optional)': 'Label ringkas (pilihan)', 'Quick label': 'Label ringkas', 'Spouse': 'Pasangan', 'Child': 'Anak', 'Parent': 'Ibu bapa', 'Client': 'Klien', 'You have reached the 15-profile limit.': 'Anda dah capai had 15 profil.', 'Add a profile name first.': 'Masukkan nama profil dulu.', 'Gross salary must be above RM 0.': 'Gaji kasar mesti lebih daripada RM 0.',
    'One free account keeps your profile, loans, and scenarios backed up everywhere.': 'Satu akaun percuma simpan profil, pinjaman dan pelan anda di semua peranti.', 'Cloud setup pending': 'Cloud belum siap', 'The app remains local and fully usable while the secure cloud connection is configured.': 'Aplikasi masih boleh digunakan sepenuhnya pada peranti ini sementara cloud disiapkan.', 'Cloud sync is on': 'Cloud sync dah hidup', 'Syncing changes': 'Sedang simpan perubahan', 'Protected in your account': 'Selamat dalam akaun anda', 'Last synced {time}': 'Kali terakhir sync {time}', 'Preparing first backup': 'Sedang siapkan backup pertama', 'Sync now': 'Sync sekarang', 'Sign out': 'Log keluar', 'Delete the cloud backup? Data on this device will stay here.': 'Padam backup cloud? Data dalam peranti ini akan kekal.', 'Delete cloud backup': 'Padam backup cloud',
    'Sign in to Spectra': 'Log masuk Spectra', 'Enter your email and we will send a secure sign-in link. No password needed.': 'Masukkan e-mel. Kami hantar pautan log masuk yang selamat - tak perlu kata laluan.', 'Email': 'E-mel', 'Sending link...': 'Sedang hantar pautan...', 'Email me a sign-in link': 'Hantar pautan log masuk', 'Local first, cloud when you choose': 'Guna sendiri dulu, cloud bila anda mahu', 'Spectra works without an account. Signing in backs up your profile, active loans, and saved scenarios so another device can restore them.': 'Spectra boleh digunakan tanpa akaun. Log masuk untuk backup profil, pinjaman aktif dan pelan supaya boleh dibuka pada peranti lain.', 'Never enter NRIC, card numbers, OTPs, or official loan documents.': 'Jangan masukkan NRIC, nombor kad, OTP atau dokumen pinjaman rasmi.', 'Export my Spectra data': 'Eksport data Spectra saya', 'Something went wrong. Please try again.': 'Ada masalah sikit. Cuba lagi.',
    'The same Spectra ring, in your chosen theme colour.': 'Cincin Spectra yang sama, ikut warna tema pilihan anda.', 'Your app icon colour and in-app accent are one shared setting.': 'Warna ikon dan warna utama dalam aplikasi berubah bersama.', 'Ads help keep Spectra free - you can go ad-free anytime.': 'Iklan bantu Spectra kekal percuma - anda boleh buang iklan bila-bila masa.', 'Planned one-time price': 'Harga sekali bayar dirancang', 'No banners, no interstitials, forever. Calculators and results stay exactly the same.': 'Tiada banner atau iklan pop-up. Kalkulator dan hasil tetap sama.', 'One purchase for this account': 'Sekali beli untuk akaun ini', 'RM88.88 is a preview price for now. Payment is not enabled yet.': 'RM88.88 cuma harga contoh buat masa ini. Bayaran belum dibuka.', 'There are no purchases to restore yet.': 'Belum ada pembelian untuk dipulihkan.', 'Restore purchase': 'Pulihkan pembelian',
    'Clear limits, plain language and no surprises.': 'Had yang jelas, bahasa mudah dan tiada kejutan.', 'Calculator disclaimer': 'Peringatan kalkulator', 'Terms of use': 'Terma penggunaan', 'Privacy notice': 'Notis privasi', 'Changes and consent': 'Perubahan & persetujuan', 'Visit the Spectra website': 'Lawati laman Spectra',
    'Spectra provides planning estimates, not financial, legal, tax, Syariah, or investment advice. Confirm all figures with the relevant bank, authority, adviser, or court.': 'Spectra beri anggaran untuk merancang, bukan nasihat kewangan, undang-undang, cukai, Syariah atau pelaburan. Semak angka akhir dengan bank, pihak berkuasa, penasihat atau mahkamah yang berkaitan.',
    'Use Spectra for lawful personal planning. Results can differ from official offers because providers use their own rules, fees, rounding, and eligibility checks. You remain responsible for decisions made using these estimates.': 'Guna Spectra untuk perancangan peribadi yang sah. Hasil mungkin berbeza daripada tawaran rasmi kerana setiap penyedia ada peraturan, yuran dan semakan sendiri. Keputusan akhir tetap tanggungjawab anda.',
    "Spectrality Enterprise operates Spectra. Your profile, calculator entries, app preferences, saved scenarios, and active-loan records stay in this browser unless you choose account sign-in. With cloud sync enabled, this data is stored in Spectra's Supabase project so it can be restored on your devices. Website infrastructure, authentication, database, and font providers may process email, IP address, device information, and service logs to deliver and secure the app. You can delete the cloud backup from Account & cloud sync. Clearing browser site data removes the local copy. Do not enter NRIC, OTPs, card details, passwords, or official documents.": 'Spectrality Enterprise mengendalikan Spectra. Profil, input kalkulator, pilihan aplikasi, pelan disimpan dan rekod pinjaman aktif kekal dalam pelayar ini kecuali anda log masuk. Bila cloud sync hidup, data ini disimpan dalam projek Supabase Spectra supaya boleh dipulihkan pada peranti anda. Penyedia laman, log masuk, pangkalan data dan fon mungkin memproses e-mel, IP, maklumat peranti dan log teknikal untuk menjalankan serta melindungi aplikasi. Anda boleh padam backup cloud melalui Akaun & cloud sync. Jangan masukkan NRIC, OTP, nombor kad, kata laluan atau dokumen rasmi.',
    'Your acceptance is saved on this device with the notice version and date. If these terms or data practices materially change, Spectra can ask you to review and agree again.': 'Persetujuan, versi notis dan tarikhnya disimpan pada peranti ini. Jika terma atau cara data digunakan berubah dengan ketara, Spectra akan minta anda semak dan setuju sekali lagi.',
    'Before you continue': 'Sebelum kita mula', 'A quick check before we start': 'Semak sekejap dulu', 'Spectra provides planning estimates only, not financial, legal, tax, Syariah, or investment advice. Results may differ from official decisions and offers.': 'Spectra beri anggaran perancangan saja, bukan nasihat kewangan, undang-undang, cukai, Syariah atau pelaburan. Hasil mungkin berbeza daripada keputusan dan tawaran rasmi.', "Your data stays in this browser unless you choose to sign in. When cloud sync is enabled, your profile, saved scenarios, and active-loan records are sent to Spectra's Supabase account storage. Service providers also process technical logs needed to deliver and secure the website.": 'Data kekal dalam pelayar ini kecuali anda log masuk. Bila cloud sync hidup, profil, pelan disimpan dan rekod pinjaman aktif dihantar ke storan akaun Supabase Spectra. Penyedia perkhidmatan juga memproses log teknikal untuk menjalankan dan melindungi laman ini.', 'I have read and agree to the Terms of Use and Privacy Notice.': 'Saya dah baca dan setuju dengan Terma Penggunaan dan Notis Privasi.', 'Agree and continue': 'Setuju dan teruskan', 'Visit spectramsia.com': 'Lawati spectramsia.com',
    'Device and cloud data are up to date.': 'Data peranti dan cloud dah sama.', 'This device is now backed up.': 'Peranti ini dah dibackup.', 'Changes saved to cloud.': 'Perubahan dah disimpan ke cloud.', 'Check your email and open the secure sign-in link.': 'Semak e-mel dan buka pautan log masuk yang kami hantar.', 'Signed out. Your data remains available on this device.': 'Dah log keluar. Data masih ada dalam peranti ini.', 'Cloud backup deleted and account signed out. Local data remains on this device.': 'Backup cloud dah dipadam dan akaun dah log keluar. Data dalam peranti ini masih ada.',
    'Not signed in': 'Belum log masuk', 'Use {colour} theme colour': 'Guna warna tema {colour}',
    'Edit {name}': 'Edit {name}', 'Edit loan': 'Edit pinjaman', 'Delete {name}': 'Padam {name}', 'Delete loan': 'Padam pinjaman', 'Remove {name} from comparison': 'Keluarkan {name} daripada perbandingan', 'Select {name} for comparison': 'Pilih {name} untuk dibandingkan', 'Re-save this calculation to unlock comparison': 'Simpan semula kiraan ini untuk buka perbandingan', 'Select for comparison': 'Pilih untuk dibandingkan', 'Track {name} as an active loan': 'Pantau {name} sebagai pinjaman aktif', 'Track active loan': 'Pantau pinjaman aktif', 'Delete scenario': 'Padam senario', 'Scenario comparison': 'Perbandingan senario',
    'Uses a standard reducing-balance installment estimate.': 'Guna anggaran ansuran baki berkurang yang biasa.', 'Stamp duty and professional fees are planning estimates. Replace them with official quotes when available.': 'Duti setem dan yuran profesional cuma anggaran. Tukar kepada sebut harga rasmi bila dah ada.', 'Malaysia car hire purchase quotes commonly use flat-rate interest.': 'Pinjaman kereta di Malaysia biasanya guna kadar rata.', 'The effective rate helps compare against reducing-balance financing.': 'Kadar efektif bantu anda banding dengan pembiayaan baki berkurang.', 'Actual bank quotes may include fees, rebates, insurance, settlement rules, and different rounding.': 'Tawaran bank sebenar mungkin ada yuran, rebat, insurans, syarat penyelesaian dan cara pembundaran lain.',
    'Entered payment is below the first estimated minimum payment.': 'Bayaran yang dimasukkan lebih rendah daripada anggaran minimum pertama.', 'Minimum-payment projection recalculates each month from the editable assumptions.': 'Anggaran bayaran minimum dikira semula setiap bulan ikut angka yang anda isi.', 'Actual statement cycles, compounding, fees, and promotions can differ.': 'Kitaran penyata, faedah berganda, yuran dan promosi sebenar mungkin berbeza.', 'PTPTN statements and official schedules should be checked for actual service charge treatment.': 'Semak penyata dan jadual rasmi PTPTN untuk caj perkhidmatan sebenar.',
  },
  zh: {
    'Set it once - every calculator can use it to check what fits your budget.': '设定一次就好，之后每个计算器都能帮你看预算合不合适。', 'Income & deductions': '收入与扣除', 'Gross monthly salary': '每月税前薪资', 'EPF rate': 'EPF 比率', 'PCB / tax': 'PCB / 税务', 'SOCSO and EIS are estimated automatically for this planning view.': 'SOCSO 和 EIS 会自动估算。', 'Cashflow plan': '现金流规划', 'Living expenses': '生活费', 'Investment view': '投资视图', 'Not configured': '还没设定', 'Room left': '还有空间', 'Profile saved': '资料已保存', 'Save profile': '保存资料',
    'New salary profile': '新薪资资料', '{count} of 15 slots used - name it for a family member or client.': '已用 {count}/15 个位置，可以用家人或客户的名字。', 'Profile name': '资料名称', 'e.g. Wife, Mum, Client - Aiman': '例如：太太、妈妈、客户 - Aiman', 'Quick label (optional)': '快速标签（可选）', 'Quick label': '快速标签', 'Spouse': '配偶', 'Child': '孩子', 'Parent': '父母', 'Client': '客户', 'You have reached the 15-profile limit.': '已经达到 15 份资料的上限。', 'Add a profile name first.': '先填上资料名称。', 'Gross salary must be above RM 0.': '薪资必须高于 RM 0。',
    'One free account keeps your profile, loans, and scenarios backed up everywhere.': '一个免费账户，就能在不同设备备份资料、贷款和方案。', 'Cloud setup pending': '云端还没设定好', 'The app remains local and fully usable while the secure cloud connection is configured.': '云端设定期间，App 还是可以在这台设备正常使用。', 'Cloud sync is on': '云同步已开启', 'Syncing changes': '正在同步更改', 'Protected in your account': '已保存在你的账户', 'Last synced {time}': '上次同步 {time}', 'Preparing first backup': '正在准备第一次备份', 'Sync now': '现在同步', 'Sign out': '登出', 'Delete the cloud backup? Data on this device will stay here.': '删除云备份？这台设备里的数据会保留。', 'Delete cloud backup': '删除云备份', 'Sign in to Spectra': '登录 Spectra', 'Enter your email and we will send a secure sign-in link. No password needed.': '输入电邮，我们会发安全登录链接，不需要密码。', 'Email': '电邮', 'Sending link...': '正在发送...', 'Email me a sign-in link': '发登录链接给我', 'Local first, cloud when you choose': '先存在本机，想要时才用云端', 'Export my Spectra data': '导出我的 Spectra 数据', 'Something went wrong. Please try again.': '出了一点问题，再试一次。',
    'The same Spectra ring, in your chosen theme colour.': '使用你选的主题颜色显示 Spectra 圆环。', 'Your app icon colour and in-app accent are one shared setting.': 'App 图标和里面的主题色会一起改变。', 'Ads help keep Spectra free - you can go ad-free anytime.': '广告让 Spectra 继续免费，你也可以随时移除广告。', 'Planned one-time price': '计划一次性价格', 'No banners, no interstitials, forever. Calculators and results stay exactly the same.': '不再有横幅或弹出广告，计算器和结果不会变。', 'One purchase for this account': '这个账户一次购买', 'Restore purchase': '恢复购买',
    'Clear limits, plain language and no surprises.': '说清楚限制，简单直接。', 'Calculator disclaimer': '计算器说明', 'Terms of use': '使用条款', 'Privacy notice': '隐私说明', 'Changes and consent': '更改与同意', 'Visit the Spectra website': '前往 Spectra 网站',
    'Spectra provides planning estimates, not financial, legal, tax, Syariah, or investment advice. Confirm all figures with the relevant bank, authority, adviser, or court.': 'Spectra 只提供规划用的估算，不是财务、法律、税务、Syariah 或投资建议。最后数字请和相关银行、机构、顾问或法庭确认。',
    'Use Spectra for lawful personal planning. Results can differ from official offers because providers use their own rules, fees, rounding, and eligibility checks. You remain responsible for decisions made using these estimates.': '请合法地使用 Spectra 做个人规划。由于每家机构的规则、费用和审核不同，结果可能和正式报价不一样。你需要为最后决定负责。',
    "Spectrality Enterprise operates Spectra. Your profile, calculator entries, app preferences, saved scenarios, and active-loan records stay in this browser unless you choose account sign-in. With cloud sync enabled, this data is stored in Spectra's Supabase project so it can be restored on your devices. Website infrastructure, authentication, database, and font providers may process email, IP address, device information, and service logs to deliver and secure the app. You can delete the cloud backup from Account & cloud sync. Clearing browser site data removes the local copy. Do not enter NRIC, OTPs, card details, passwords, or official documents.": 'Spectra 由 Spectrality Enterprise 运营。除非你选择登录，个人资料、计算内容、App 设置、已保存方案和贷款记录都留在这个浏览器。开启云同步后，数据会存在 Spectra 的 Supabase 项目，方便在其他设备恢复。网站、登录、数据库和字体服务商可能处理电邮、IP、设备资料和技术记录来运行与保护 App。请不要输入 NRIC、OTP、卡号、密码或正式文件。',
    'Before you continue': '继续之前', 'A quick check before we start': '开始前快速看一下', 'Spectra provides planning estimates only, not financial, legal, tax, Syariah, or investment advice. Results may differ from official decisions and offers.': 'Spectra 只帮你做规划估算，不是财务、法律、税务、Syariah 或投资建议。结果可能和正式决定或报价不同。', "Your data stays in this browser unless you choose to sign in. When cloud sync is enabled, your profile, saved scenarios, and active-loan records are sent to Spectra's Supabase account storage. Service providers also process technical logs needed to deliver and secure the website.": '除非你选择登录，否则数据只留在这个浏览器。开启云同步后，个人资料、保存的方案和贷款记录会存进 Spectra 的 Supabase 账户空间。服务商也会处理运行和保护网站所需的技术记录。', 'I have read and agree to the Terms of Use and Privacy Notice.': '我已阅读并同意使用条款和隐私说明。', 'Agree and continue': '同意并继续', 'Visit spectramsia.com': '前往 spectramsia.com',
    'Device and cloud data are up to date.': '这台设备和云端资料已经同步。', 'This device is now backed up.': '这台设备已经备份好了。', 'Changes saved to cloud.': '更改已保存到云端。', 'Check your email and open the secure sign-in link.': '去看一下电邮，然后打开安全登录链接。', 'Signed out. Your data remains available on this device.': '已登出，资料还留在这台设备。', 'Cloud backup deleted and account signed out. Local data remains on this device.': '云备份已删除，账户也已登出。本机资料还在。',
    'Not signed in': '还没登录', 'Use {colour} theme colour': '使用 {colour} 主题色',
    'Edit {name}': '编辑 {name}', 'Edit loan': '编辑贷款', 'Delete {name}': '删除 {name}', 'Delete loan': '删除贷款', 'Remove {name} from comparison': '从比较中移除 {name}', 'Select {name} for comparison': '选择 {name} 来比较', 'Re-save this calculation to unlock comparison': '重新保存这个计算后就能比较', 'Select for comparison': '选择来比较', 'Track {name} as an active loan': '把 {name} 加到当前贷款', 'Track active loan': '跟进当前贷款', 'Delete scenario': '删除方案', 'Scenario comparison': '方案比较',
    'Uses a standard reducing-balance installment estimate.': '使用常见的余额递减供款估算。', 'Stamp duty and professional fees are planning estimates. Replace them with official quotes when available.': '印花税和专业费用只是估算，有正式报价后记得换上。', 'Malaysia car hire purchase quotes commonly use flat-rate interest.': '马来西亚车贷通常使用平息算法。', 'The effective rate helps compare against reducing-balance financing.': '实际利率可以帮你和余额递减贷款做比较。', 'Actual bank quotes may include fees, rebates, insurance, settlement rules, and different rounding.': '银行正式报价可能还包括费用、回扣、保险、结清规则和不同的四舍五入方式。',
    'Entered payment is below the first estimated minimum payment.': '你填的还款额低于第一期预计最低还款。', 'Minimum-payment projection recalculates each month from the editable assumptions.': '最低还款估算会按照你填的设定每月重新计算。', 'Actual statement cycles, compounding, fees, and promotions can differ.': '实际账单周期、复利、费用和优惠可能不同。', 'PTPTN statements and official schedules should be checked for actual service charge treatment.': '实际服务费请查看 PTPTN 账单和官方还款表。',
  },
  ta: {
    'Set it once - every calculator can use it to check what fits your budget.': 'ஒரு முறை அமைத்தால் போதும் - எல்லா கணக்கிடுகளும் உங்கள் பஜ்ஜெட்டைப் பார்க்கும்.', 'Income & deductions': 'வருமானம் & பிடித்தம்', 'Gross monthly salary': 'மாத மொத்த சம்பளம்', 'EPF rate': 'EPF விகிதம்', 'PCB / tax': 'PCB / வரி', 'Cashflow plan': 'பணப்புழக்க திட்டம்', 'Living expenses': 'வாழ்க்கைச் செலவு', 'Investment view': 'முதலீட்டு பார்வை', 'Not configured': 'இன்னும் அமைக்கவில்லை', 'Room left': 'மீதி இடம்', 'Profile saved': 'சுயவிவரம் சேமித்தாயிற்று', 'Save profile': 'சுயவிவரத்தை சேமி',
    'New salary profile': 'புதிய சம்பள விவரம்', '{count} of 15 slots used - name it for a family member or client.': '15-ல் {count} இடம் பயன்படுத்தியாயிற்று - குடும்பம் அல்லது வாடிக்கையாளர் பெயரைக் கொடு.', 'Profile name': 'விவரப் பெயர்', 'e.g. Wife, Mum, Client - Aiman': 'உதாரணம்: மனைவி, அம்மா, வாடிக்கையாளர் - Aiman', 'Quick label (optional)': 'சிறு லேபிள் (விருப்பம்)', 'Spouse': 'துணை', 'Child': 'பிள்ளை', 'Parent': 'பெற்றோர்', 'Client': 'வாடிக்கையாளர்',
    'One free account keeps your profile, loans, and scenarios backed up everywhere.': 'ஒரு இலவச கணக்கு உங்கள் விவரம், கடன், திட்டத்தை எல்லா சாதனத்திலும் backup செய்யும்.', 'Cloud setup pending': 'Cloud இன்னும் தயாராகவில்லை', 'Cloud sync is on': 'Cloud sync இயங்குகிறது', 'Syncing changes': 'மாற்றங்கள் sync ஆகிறது', 'Protected in your account': 'உங்கள் கணக்கில் சேமித்தாயிற்று', 'Last synced {time}': 'கடைசி sync {time}', 'Preparing first backup': 'முதல் backup தயாராகிறது', 'Sync now': 'இப்போது sync', 'Sign out': 'வெளியேறு', 'Delete cloud backup': 'Cloud backup-ஐ நீக்கு', 'Sign in to Spectra': 'Spectra-வில் நுழை', 'Enter your email and we will send a secure sign-in link. No password needed.': 'உங்கள் email-ஐ போடுங்கள். பாதுகாப்பான login link அனுப்புவோம் - password தேவையில்லை.', 'Email': 'Email', 'Sending link...': 'Link அனுப்புகிறது...', 'Email me a sign-in link': 'Login link அனுப்பு', 'Local first, cloud when you choose': 'முதலில் இந்த சாதனம், விரும்பினால் cloud', 'Export my Spectra data': 'என் Spectra data-வை export செய்',
    'The same Spectra ring, in your chosen theme colour.': 'நீங்கள் தேர்ந்த தீம் நிறத்தில் Spectra வளையம்.', 'Your app icon colour and in-app accent are one shared setting.': 'App ஐகான் நிறமும் உள்ளே உள்ள நிறமும் ஒன்றாக மாறும்.', 'Ads help keep Spectra free - you can go ad-free anytime.': 'விளம்பரம் Spectra-வை இலவசமாக வைக்க உதவும் - விரும்பினால் நீக்கலாம்.', 'Planned one-time price': 'திட்டமிட்ட ஒருமுறை விலை', 'One purchase for this account': 'இந்த கணக்குக்கு ஒரு முறை வாங்கினால் போதும்', 'Restore purchase': 'வாங்கியதை மீட்டெடு',
    'Clear limits, plain language and no surprises.': 'தெளிவான வரம்பு, எளிய மொழி.', 'Calculator disclaimer': 'கணக்கிடு குறிப்பு', 'Terms of use': 'பயன்பாட்டு விதிகள்', 'Privacy notice': 'தனியுரிமை அறிவிப்பு', 'Changes and consent': 'மாற்றம் & ஒப்புதல்', 'Visit the Spectra website': 'Spectra இணையதளத்தைப் பார்',
    'Spectra provides planning estimates, not financial, legal, tax, Syariah, or investment advice. Confirm all figures with the relevant bank, authority, adviser, or court.': 'Spectra திட்டமிடுவதற்கான கணக்கை மட்டும் தரும். இது நிதி, சட்டம், வரி, Syariah அல்லது முதலீட்டு ஆலோசனை அல்ல. இறுதி எண்களை வங்கி அல்லது சரியான அதிகாரியிடம் உறுதி செய்யுங்கள்.',
    'Use Spectra for lawful personal planning. Results can differ from official offers because providers use their own rules, fees, rounding, and eligibility checks. You remain responsible for decisions made using these estimates.': 'Spectra-வை சட்டப்பூர்வமான தனிப்பட்ட திட்டத்திற்கு பயன்படுத்துங்கள். ஒவ்வொரு நிறுவனத்தின் விதி, கட்டணம், சரிபார்ப்பு மாறும்; அதனால் அதிகாரப்பூர்வ சலுகை வேறாக இருக்கலாம். இறுதி முடிவு உங்களுடையது.',
    'Before you continue': 'தொடர்வதற்கு முன்', 'A quick check before we start': 'தொடங்கும் முன் சிறு சரிபார்ப்பு', 'Spectra provides planning estimates only, not financial, legal, tax, Syariah, or investment advice. Results may differ from official decisions and offers.': 'Spectra திட்டமிட உதவும் கணக்கை மட்டும் தரும். இது நிதி, சட்டம், வரி, Syariah அல்லது முதலீட்டு ஆலோசனை அல்ல. அதிகாரப்பூர்வ முடிவுகள் வேறாக இருக்கலாம்.', "Your data stays in this browser unless you choose to sign in. When cloud sync is enabled, your profile, saved scenarios, and active-loan records are sent to Spectra's Supabase account storage. Service providers also process technical logs needed to deliver and secure the website.": 'நீங்கள் login செய்யாவிட்டால் data இந்த browser-லேயே இருக்கும். Cloud sync போட்டால் profile, சேமித்த திட்டங்கள், கடன் பதிவுகள் Spectra Supabase கணக்கில் சேமிக்கப்படும். இணையதளத்தை இயக்கவும் பாதுகாக்கவும் தேவையான technical logs-ஐ சேவை நிறுவனங்கள் process செய்யலாம்.', 'I have read and agree to the Terms of Use and Privacy Notice.': 'பயன்பாட்டு விதிகள் மற்றும் தனியுரிமை அறிவிப்பை படித்து ஒப்புக்கொள்கிறேன்.', 'Agree and continue': 'ஒப்புக்கொண்டு தொடர்', 'Visit spectramsia.com': 'spectramsia.com-ஐப் பார்',
    'Device and cloud data are up to date.': 'சாதனமும் cloud data-வும் sync ஆயிற்று.', 'This device is now backed up.': 'இந்த சாதனம் backup ஆயிற்று.', 'Changes saved to cloud.': 'மாற்றங்கள் cloud-ல் சேமித்தாயிற்று.', 'Check your email and open the secure sign-in link.': 'Email-ஐ பார்த்து பாதுகாப்பான login link-ஐ திறக்கவும்.', 'Signed out. Your data remains available on this device.': 'வெளியேறிவிட்டீர்கள். Data இந்த சாதனத்தில் இன்னும் இருக்கிறது.', 'Cloud backup deleted and account signed out. Local data remains on this device.': 'Cloud backup நீக்கி account-லிருந்து வெளியேறிவிட்டீர்கள். இந்த சாதனத்தில் data இன்னும் இருக்கிறது.',
    'Not signed in': 'இன்னும் login செய்யவில்லை', 'Use {colour} theme colour': '{colour} தீம் நிறத்தை பயன்படுத்து',
    'Edit {name}': '{name}-ஐ திருத்து', 'Edit loan': 'கடனை திருத்து', 'Delete {name}': '{name}-ஐ நீக்கு', 'Delete loan': 'கடனை நீக்கு', 'Remove {name} from comparison': 'ஒப்பீட்டிலிருந்து {name}-ஐ நீக்கு', 'Select {name} for comparison': 'ஒப்பிட {name}-ஐ தேர்ந்தெடு', 'Re-save this calculation to unlock comparison': 'ஒப்பிட இந்தக் கணக்கை மீண்டும் சேமி', 'Select for comparison': 'ஒப்பிட தேர்ந்தெடு', 'Track {name} as an active loan': '{name}-ஐ நடப்பு கடனாக கண்காணி', 'Track active loan': 'நடப்பு கடனை கண்காணி', 'Delete scenario': 'திட்டத்தை நீக்கு', 'Scenario comparison': 'திட்ட ஒப்பீடு',
    'Uses a standard reducing-balance installment estimate.': 'வழக்கமான குறையும் மீதி தவணை கணக்கைப் பயன்படுத்துகிறது.', 'Stamp duty and professional fees are planning estimates. Replace them with official quotes when available.': 'Stamp duty, professional fee இப்போது ஒரு கணக்கு மட்டும். அதிகாரப்பூர்வ quote கிடைத்ததும் மாற்றுங்கள்.', 'Malaysia car hire purchase quotes commonly use flat-rate interest.': 'மலேசிய கார் கடன் பொதுவாக flat-rate வட்டியைப் பயன்படுத்தும்.', 'The effective rate helps compare against reducing-balance financing.': 'Effective rate மூலம் reducing-balance கடனோடு ஒப்பிடலாம்.', 'Actual bank quotes may include fees, rebates, insurance, settlement rules, and different rounding.': 'வங்கியின் உண்மையான quote-ல் fee, rebate, insurance, settlement விதி, rounding மாறலாம்.',
    'Entered payment is below the first estimated minimum payment.': 'நீங்கள் போட்ட தொகை முதல் minimum payment கணக்கைவிட குறைவு.', 'Minimum-payment projection recalculates each month from the editable assumptions.': 'நீங்கள் போட்ட விவரங்களைக் கொண்டு minimum payment ஒவ்வொரு மாதமும் மீண்டும் கணக்கிடப்படும்.', 'Actual statement cycles, compounding, fees, and promotions can differ.': 'உண்மையான statement cycle, வட்டி, fee, promotion மாறலாம்.', 'PTPTN statements and official schedules should be checked for actual service charge treatment.': 'உண்மையான service charge-க்கு PTPTN statement மற்றும் அதிகாரப்பூர்வ schedule-ஐ பாருங்கள்.',
  },
};
